
# Optimized Domain Agent Configuration with Environment Variable Support
# This file supports environment variables using ${VAR_NAME:default_value} syntax

global:
  cache_size: ${DOMAIN_CACHE_SIZE:256}
  max_concurrent_analyses: ${DOMAIN_MAX_CONCURRENT:10}
  error_threshold: ${DOMAIN_ERROR_THRESHOLD:20}
  config_reload_interval: 300
  enable_hot_reload: true
  performance_monitoring: true
  detailed_logging: ${DOMAIN_DETAILED_LOGGING:false}
  
  timeouts:
    analysis_timeout: ${DOMAIN_ANALYSIS_TIMEOUT:30}
    evidence_processing_timeout: ${DOMAIN_EVIDENCE_TIMEOUT:60}
    orchestration_timeout: ${DOMAIN_ORCHESTRATION_TIMEOUT:120}

financial:
  keywords:
    primary:
      - market
      - trading
      - investment
      - portfolio
      - stock
      - bond
      - forex
      - currency
      - financial
      - economics
    secondary:
      - commodity
      - derivative
      - equity
      - debt
      - monetary
      - fiscal
      - inflation
      - interest rate
      - volatility
      - risk
    contextual:
      - central bank
      - fed
      - ecb
      - bank of japan
      - earnings
      - revenue
      - profit
      - loss
      - dividend
      - yield
  
  analysis_patterns:
    trend_analysis:
      - uptrend
      - downtrend
      - sideways
      - bullish
      - bearish
    risk_analysis:
      - high risk
      - low risk
      - volatile
      - stable
      - conservative
      - aggressive
  
  thresholds:
    relevance_score: ${FINANCIAL_RELEVANCE_SCORE:0.3}
    confidence_threshold: ${FINANCIAL_CONFIDENCE:0.6}
    risk_score_threshold: ${FINANCIAL_RISK_THRESHOLD:0.7}
    min_evidence_count: 3
  
  enabled: true
  priority: 8

technical:
  keywords:
    primary:
      - technical analysis
      - chart
      - pattern
      - indicator
      - signal
      - support
      - resistance
      - trend
      - momentum
    secondary:
      - oscillator
      - moving average
      - rsi
      - macd
      - bollinger bands
      - fibonacci
      - candlestick
      - volume
      - breakout
      - reversal
    contextual:
      - bullish
      - bearish
      - overbought
      - oversold
      - divergence
      - consolidation
      - pennant
      - flag
      - triangle
      - head and shoulders
  
  thresholds:
    relevance_score: ${TECHNICAL_RELEVANCE_SCORE:0.4}
    confidence_threshold: ${TECHNICAL_CONFIDENCE:0.7}
    min_evidence_count: 2
  
  enabled: true
  priority: 7

market:
  keywords:
    primary:
      - market
      - sector
      - industry
      - economy
      - economic
      - gdp
      - employment
      - consumer
    secondary:
      - sentiment
      - outlook
      - forecast
      - prediction
      - analysis
      - research
      - report
      - data
    contextual:
      - bull market
      - bear market
      - recession
      - expansion
      - cycle
      - seasonal
  
  thresholds:
    relevance_score: ${MARKET_RELEVANCE_SCORE:0.25}
    confidence_threshold: ${MARKET_CONFIDENCE:0.65}
    min_evidence_count: 3
  
  enabled: true
  priority: 6

risk:
  keywords:
    primary:
      - risk
      - volatility
      - uncertainty
      - hedge
      - protection
      - insurance
      - safety
      - security
    secondary:
      - diversification
      - correlation
      - exposure
      - mitigation
      - management
      - assessment
      - analysis
      - measurement
    contextual:
      - black swan
      - tail risk
      - systematic
      - idiosyncratic
      - credit risk
      - market risk
      - operational risk
  
  thresholds:
    relevance_score: ${RISK_RELEVANCE_SCORE:0.35}
    confidence_threshold: ${RISK_CONFIDENCE:0.8}
    min_evidence_count: 2
  
  enabled: true
  priority: 9
